# Generated by Django 4.1 on 2022-08-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_pairing'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheese',
            name='pairings',
            field=models.ManyToManyField(to='main_app.pairing'),
        ),
    ]
